([<masc><fem>]<nom><sg>|\
<neut>[<nom><voc><acc>]<sg>|\
is<gen><sg>|\
i\_<dat><sg>|\
em[<masc><fem>]<acc><sg>|\
e<abl><sg>|\
e\_s[<masc><fem>][<nom><voc>]<pl>|\
a<neut>[<nom><voc><acc>]<pl>|\
um<gen><pl>|\
ibus<dat><pl>|\
e\_s[<masc><fem>]<acc><pl>|\
ibus<abl><pl>)
