(a[<nom><voc>]<sg>|\
a\_s<nom><sg>|\
a\_i\_<gen><sg><poetic>|\
ae<gen><sg>|\
ae<gen><sg>|\
ae<dat><sg>|\
am<acc><sg>|\
a\_n<acc><sg>|\
a\_<voc><sg>|\
a\_<abl><sg>|\
a\_<abl><sg>|\
ae[<nom><voc>]<pl>|\
a\_rum<gen><pl>|\
i\_s<dat><pl>|\
a\_s<acc><pl>|\
i\_s<abl><pl>)
