(as[<masc><fem>][<nom><voc>]<sg>|\
as<neut>[<nom><voc><acc>]<sg>|\
antis<gen><sg>|\
anti\_<dat><sg>|\
antem[<masc><fem>]<acc><sg>|\
ante<abl><sg>|\
ante\_s[<masc><fem>][<nom><voc>]<pl>|\
anta<neut>[<nom><voc><acc>]<pl>|\
antum<gen><pl>|\
antibus<dat><pl>|\
ante\_s[<masc><fem>]<acc><pl>|\
antibus<abl><pl>)
