(a^da<acc>|\
a^s<nom><sg>|\
a^dis<gen><sg>|\
a^di\_<dat><sg>|\
a^dem[<masc><fem>]<acc><sg>|\
a^de<abl><sg>|\
a^de\_s[<masc><fem>][<nom><voc>]<pl>|\
a^da<neut>[<nom><voc><acc>]<pl>|\
a^dum<gen><pl>|\
a^dibus<dat><pl>|\
a^das<acc><pl>|\
a^de\_s[<masc><fem>]<acc><pl>|\
a^dibus<abl><pl>)
