(e\_s<fem>[<nom><voc>]<sg>|\
eris<gen><sg>|\
eri\_<dat><sg>|\
erem[<masc><fem>]<acc><sg>|\
ere<abl><sg>|\
ere\_s[<masc><fem>][<nom><voc>]<pl>|\
era<neut>[<nom><voc><acc>]<pl>|\
erum<gen><pl>|\
eribus<dat><pl>|\
ere\_s[<masc><fem>]<acc><pl>|\
eribus<abl><pl>)
