(e\_s<nom><sg>|\
a[<nom><voc>]<sg>|\
a\_i\_<gen><sg><poetic>|\
ae<gen><sg>|\
ae<gen><sg>|\
i\_<masc><gen><sg>|\
ae<dat><sg>|\
am<acc><sg>|\
e\_m<acc><sg>|\
e\_n<acc><sg>|\
e\_<voc><sg>|\
a\_<abl><sg>|\
e\_<abl><sg>|\
ae[<nom><voc>]<pl>|\
a\_rum<gen><pl>|\
i\_s<dat><pl>|\
a\_s<acc><pl>|\
as<acc><pl>|\
i\_s<abl><pl>)
