(e\_s[<masc><fem>]<nom><sg>|\
e\_i\_<gen><sg>|\
e\_i\_<dat><sg>|\
em[<masc><fem>]<acc><sg>|\
e\_<abl><sg>|\
e\_s[<masc><fem>]<nom><pl>|\
e\_rum<gen><pl>|\
e\_bus<dat><pl>|\
e\_s[<masc><fem>]<acc><pl>|\
e\_bus<abl><pl>)
