(e\_s[<masc><fem>]<nom><sg>|\
e\_<gen><sg><poetic><early>|\
ei\_<gen><sg>|\
ei\_<dat><sg>|\
e\_<dat><sg><poetic><early>|\
em[<masc><fem>]<acc><sg>|\
e\_<abl><sg>|\
e\_s[<masc><fem>]<nom><pl>|\
e\_rum<gen><pl>|\
e\_bus<dat><pl>|\
e\_s[<masc><fem>]<acc><pl>|\
e\_bus<abl><pl>)
