(es[<masc><fem>]<nom><sg>|\
itis<gen><sg>|\
iti\_<dat><sg>|\
item[<masc><fem>]<acc><sg>|\
ite<abl><sg>|\
ite\_s[<masc><fem>][<nom><voc>]<pl>|\
ita<neut>[<nom><voc><acc>]<pl>|\
itum<gen><pl>|\
itibus<dat><pl>|\
ite\_s[<masc><fem>]<acc><pl>|\
itibus<abl><pl>)
