(ex<nom><sg>|\
icis<gen><sg>|\
ici\_<dat><sg>|\
icem[<masc><fem>]<acc><sg>|\
ice<abl><sg>|\
ice\_s[<masc><fem>][<nom><voc>]<pl>|\
ica<neut>[<nom><voc><acc>]<pl>|\
icum<gen><pl>|\
icibus<dat><pl>|\
ice\_s[<masc><fem>]<acc><pl>|\
icibus<abl><pl>)
