(ios[<masc><fem>]<nom><sg>|\
ium<neut>[<nom><voc><acc>]<sg>|\
ion<neut>[<nom><voc><acc>]<sg>|\
iom<neut>[<nom><voc><acc>]<sg><early>|\
i\_<gen><sg>|\
ii\_<gen><sg>|\
io\_<dat><sg>|\
ium[<masc><fem>]<acc><sg>|\
iom[<masc><fem>]<acc><sg><early>|\
ie<voc><sg>|\
i[<masc><fem>]<voc><sg>|\
io\_<abl><sg>|\
ii\_[<masc><fem>][<nom><voc>]<pl>|\
ia<neut>[<nom><voc><acc>]<pl>|\
io\_rum<gen><pl>|\
iu\_m<gen><pl><poetic>|\
ii\_s<dat><pl>|\
io\_s[<masc><fem>]<acc><pl>|\
ii\_s<abl><pl>|\
ie\_<adverbial>)
