(is[<masc><fem>]<nom><sg>|\
os<neut>[<nom><acc>]<sg>|\
eos[<masc><fem><neut>]<gen><sg>|\
i\_[<masc><fem><neut>]<dat><sg>|\
in[<masc><fem>]<acc><sg>|\
i\_[<masc><fem><neut>]<abl><sg>|\
e\_s[<masc><fem>][<nom><voc>]<pl>|\
ia<neut>[<nom><voc><acc>]<pl>|\
ea<neut>[<nom><acc>]<pl>|\
ium<gen><pl>|\
eo\_n[<masc><fem><neut>]<gen><pl>|\
ibus<dat><pl>|\
eis[<masc><fem>]<acc><pl>|\
i\_s[<masc><fem>]<acc><pl>|\
e\_s[<masc><fem>]<acc><pl>|\
ibus<abl><pl>)
