(ix[<nom><voc>]<sg>|\
i\_cis<gen><sg>|\
i\_ci\_<dat><sg>|\
i\_cem[<masc><fem>]<acc><sg>|\
i\_ce<abl><sg>|\
i\_ce\_s[<masc><fem>][<nom><voc>]<pl>|\
i\_ca<neut>[<nom><voc><acc>]<pl>|\
i\_cum<gen><pl>|\
i\_cibus<dat><pl>|\
i\_ce\_s[<masc><fem>]<acc><pl>|\
i\_cibus<abl><pl>)
