(ma<nom><sg>|\
ma^tis<gen><sg>|\
ma^ti\_<dat><sg>|\
ma^tem[<masc><fem>]<acc><sg>|\
ma^te<abl><sg>|\
ma^te\_s[<masc><fem>][<nom><voc>]<pl>|\
ma^ta<neut>[<nom><voc><acc>]<pl>|\
ma^tum<gen><pl>|\
ma^tibus<dat><pl>|\
ma^te\_s[<masc><fem>]<acc><pl>|\
ma^tibus<abl><pl>)
