(men[<nom><voc>]<sg>|\
mi^nis<gen><sg>|\
mi^ni\_<dat><sg>|\
mi^nem[<masc><fem>]<acc><sg>|\
men<neut><acc><sg>|\
mi^ne<abl><sg>|\
mi^ne\_s[<masc><fem>][<nom><voc>]<pl>|\
mi^na<neut>[<nom><voc><acc>]<pl>|\
mi^num<gen><pl>|\
mi^nibus<dat><pl>|\
mi^ne\_s[<masc><fem>]<acc><pl>|\
mi^nibus<abl><pl>)
