(o\_[<masc><fem>]<nom><sg>|\
i^nis<gen><sg>|\
i^ni\_<dat><sg>|\
i^nem[<masc><fem>]<acc><sg>|\
i^ne<abl><sg>|\
i^ne\_s[<masc><fem>][<nom><voc>]<pl>|\
i^na<neut>[<nom><voc><acc>]<pl>|\
i^num<gen><pl>|\
i^nibus<dat><pl>|\
i^ne\_s[<masc><fem>]<acc><pl>|\
i^nibus<abl><pl>)
