(or[<masc><fem>][<nom><voc>]<sg>|\
or<neut>[<nom><voc><acc>]<sg>|\
o^ris<gen><sg>|\
o^ri\_<dat><sg>|\
o^rem[<masc><fem>]<acc><sg>|\
o^re<abl><sg>|\
o^re\_s[<masc><fem>][<nom><voc>]<pl>|\
o^ra<neut>[<nom><voc><acc>]<pl>|\
o^rum<gen><pl>|\
o^ribus<dat><pl>|\
o^re\_s[<masc><fem>]<acc><pl>|\
o^ribus<abl><pl>)
