(or[<masc><fem>][<nom><voc>]<sg>|\
us<neut>[<nom><voc><acc>]<sg>|\
o\_ris<gen><sg>|\
o\_ri\_<dat><sg>|\
o\_rem[<masc><fem>]<acc><sg>|\
o\_re<abl><sg>|\
o\_re\_s[<masc><fem>][<nom><voc>]<pl>|\
o\_ra<neut>[<nom><voc><acc>]<pl>|\
o\_rum<gen><pl>|\
o\_ribus<dat><pl>|\
o\_re\_s[<masc><fem>]<acc><pl>|\
o\_ribus<abl><pl>)
