(s<nom><sg>|\
dis<gen><sg>|\
di\_<dat><sg>|\
dem[<masc><fem>]<acc><sg>|\
da[<masc><fem>]<acc><sg>|\
de<abl><sg>|\
de\_s[<masc><fem>][<nom><voc>]<pl>|\
da<neut>[<nom><voc><acc>]<pl>|\
dum<gen><pl>|\
dibus<dat><pl>|\
de\_s[<masc><fem>]<acc><pl>|\
das[<masc><fem>]<acc><pl>|\
dibus<abl><pl>)
