(s<nom><sg>|\
nis<gen><sg>|\
ni\_<dat><sg>|\
nem[<masc><fem>]<acc><sg>|\
na[<masc><fem>]<acc><sg>|\
ne<abl><sg>|\
ne\_s[<masc><fem>][<nom><voc>]<pl>|\
na<neut>[<nom><voc><acc>]<pl>|\
num<gen><pl>|\
nibus<dat><pl>|\
ne\_s[<masc><fem>]<acc><pl>|\
nibus<abl><pl>)
