(s<nom><sg>|\
tis<gen><sg>|\
tis<gen><sg>|\
ti\_<dat><sg>|\
ti\_<dat><sg>|\
tem[<masc><fem>]<acc><sg>|\
tem[<masc><fem>]<acc><sg>|\
te<abl><sg>|\
te\_s[<masc><fem>][<nom><voc>]<pl>|\
te\_s[<masc><fem>][<nom><voc>]<pl>|\
tia<neut>[<nom><voc><acc>]<pl>|\
ta<neut>[<nom><voc><acc>]<pl>|\
tum<gen><pl>|\
tium<gen><pl>|\
tium<gen><pl>|\
tibus<dat><pl>|\
tibus<dat><pl>|\
te\_s[<masc><fem>]<acc><pl>|\
te\_s[<masc><fem>]<acc><pl>|\
ti\_s[<masc><fem>]<acc><pl>|\
tibus<abl><pl>|\
tibus<abl><pl>)
