(ta\_s<nom><sg>|\
ta\_tis<gen><sg>|\
ta\_ti\_<dat><sg>|\
ta\_tem[<masc><fem>]<acc><sg>|\
ta\_te<abl><sg>|\
ta\_te\_s[<masc><fem>][<nom><voc>]<pl>|\
ta\_ta<neut>[<nom><voc><acc>]<pl>|\
ta\_tum<gen><pl>|\
ta\_tium<gen><pl>|\
ta\_tibus<dat><pl>|\
ta\_te\_s[<masc><fem>]<acc><pl>|\
ta\_tibus<abl><pl>)
