(u\_s[<masc><fem>][<nom><voc>]<sg>|\
u\_ris<gen><sg>|\
u\_ri\_<dat><sg>|\
u\_rem[<masc><fem>]<acc><sg>|\
u\_re<abl><sg>|\
u\_re\_s[<masc><fem>][<nom><voc>]<pl>|\
u\_ra<neut>[<nom><voc><acc>]<pl>|\
u\_rum<gen><pl>|\
u\_ribus<dat><pl>|\
u\_re\_s[<masc><fem>]<acc><pl>|\
u\_ribus<abl><pl>)
