(us[<masc><fem>]<nom><sg>|\
om<neut>[<nom><voc><acc>]<sg><early>|\
um<neut>[<nom><voc><acc>]<sg>|\
um<neut>[<nom><voc><acc>]<sg>|\
i\_<gen><sg>|\
o\_<dat><sg>|\
e\_<adverbial>|\
um[<masc><fem>]<acc><sg>|\
om[<masc><fem>]<acc><sg><early>|\
e<voc><sg>|\
e[<masc><fem>]<voc><sg>|\
o\_<abl><sg>|\
i\_[<masc><fem>][<nom><voc>]<pl>|\
a<neut>[<nom><voc><acc>]<pl>|\
o\_rum<gen><pl>|\
u\_m<gen><pl><poetic>|\
i\_s<dat><pl>|\
o\_s[<masc><fem>]<acc><pl>|\
i\_s<abl><pl>)
