(us[<masc><fem>][<nom><voc>]<sg>|\
us<neut>[<nom><voc><acc>]<sg>|\
oris<gen><sg>|\
ori\_<dat><sg>|\
orem[<masc><fem>]<acc><sg>|\
ore<abl><sg>|\
ore\_s[<masc><fem>][<nom><voc>]<pl>|\
ora<neut>[<nom><voc><acc>]<pl>|\
orum<gen><pl>|\
oribus<dat><pl>|\
ore\_s[<masc><fem>]<acc><pl>|\
oribus<abl><pl>)
