


# Permalinks
permalink:        pretty

# Setup
title:            Tabulae
tagline:          'A build system for parsing Latin'
description:      'Edit simple tables to build complete FST parsers with customizable vocabulary and rule sets.'

baseurl: '/tabulae/'


author:
  name:           'Neel Smith'


links:
  - title:  Github repository
    url:  https://github.com/neelsmith/tabulae
    external: true
