/workspace/tabulae/parsers/livy-morphology/latin.a: /workspace/tabulae/parsers/livy-morphology/symbols.fst /workspace/tabulae/parsers/livy-morphology/symbols/phonology.fst /workspace/tabulae/parsers/livy-morphology/inflection.a /workspace/tabulae/parsers/livy-morphology/acceptor.a 
%.a: %.fst
	/usr/bin/fst-compiler-utf8 $< $@
